name: Create Pull Request

on:
  push:
    branches:
      - main  # Trigger the action when pushing to 'main' branch

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the last commit message
      - name: Get last commit message
        id: commit
        run: echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"

      # Create the Pull Request using the PAT for authentication
      - name: Create Pull Request
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_PAT }}  # Use the PAT stored as a secret
        run: |
          PR_TITLE="${{ steps.commit.outputs.commit_message }}"
          gh auth login --with-token <<< "${{ secrets.MY_PAT }}"  # Authenticate using the PAT
          gh pr create --base main --head feature-branch --title "$PR_TITLE" --body "Automated PR created using PAT."