name: Liquibase MySQL Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: your_db_name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (needed for Liquibase)
        uses: actions/setup-java@v1
        with:
          java-version: '11'                # Specify the Java version you need
          distribution: 'temurin'      # Specify the JDK distribution here, 'adoptopenjdk' is common
          

      - name: Install Liquibase
        run: |
          curl -s https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.24.0/liquibase-core-4.24.0.jar -o liquibase.jar
          java -jar liquibase.jar --version

      - name: Run Liquibase update
        env:
          LIQUIBASE_URL: jdbc:mysql://uddezthursf9thpo:cApIZdrCriOROfE3LumI@bkxg4abnmdjq9yqqpy7g-mysql.services.clever-cloud.com:3306/bkxg4abnmdjq9yqqpy7g
          LIQUIBASE_USERNAME: uddezthursf9thpo
          LIQUIBASE_PASSWORD: cApIZdrCriOROfE3LumI
        run: |
          java -jar liquibase.jar \
            --url=$LIQUIBASE_URL \
            --username=$LIQUIBASE_USERNAME \
            --password=$LIQUIBASE_PASSWORD \
            update
