name: Liquibase MySQL Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: your_db_name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (needed for Liquibase)
        uses: actions/setup-java@v1
        with:
          java-version: '11'                # Specify the Java version you need
          distribution: 'temurin'      # Specify the JDK distribution here, 'adoptopenjdk' is common
          
      - name: Install Liquibase CLI
        run: |
          curl -L "https://github.com/liquibase/liquibase/releases/download/v4.30.0/liquibase-4.30.0.tar.gz" -o /home/runner/work/liquibase-poc/liquibase-install/liquibase.tar.gz
          echo "Downloaded Liquibase tarball"

           # Extract the tarball into the separate directory
          tar -xzvf /home/runner/work/liquibase-poc/liquibase-install/liquibase.tar.gz -C /home/runner/work/liquibase-poc/liquibase-install
          echo "Extraction complete. Listing extracted files:"
          ls -l /home/runner/work/liquibase-poc/liquibase-install   # List extracted files

        

      - name: Move Liquibase to /opt/liquibase
        run: |
          echo "Attempting to move the extracted Liquibase folder..."
          
          # Check if the directory exists and move it
          # List the current directory to see where you are
          ls -l
          pwd

          # Search for the 'liquibase-4.30.0' folder starting from the current directory
          find "$(pwd)" -type d -name "liquibase-4.30.0"

          # Go one level up and print the directory structure
          cd ..
          pwd

          # Search for the 'liquibase-4.30.0' folder from the new directory
          find "$(pwd)" -type d -name "liquibase-4.30.0"

          # List contents of the parent directory to inspect
          ls -l

          # Grab all directories named 'liquibase-4.30.0' from the file system
          echo "Grabbing all folders named liquibase-4.30.0"
          find / -type d -name "liquibase-4.30.0"




      - name: Set LIQUIBASE_HOME environment variable
        run: echo "LIQUIBASE_HOME=/opt/liquibase" >> $GITHUB_ENV

      - name: Run Liquibase update
        run: $LIQUIBASE_HOME/liquibase --url=jdbc:mysql://uddezthursf9thpo:cApIZdrCriOROfE3LumI@bkxg4abnmdjq9yqqpy7g-mysql.services.clever-cloud.com:3306/bkxg4abnmdjq9yqqpy7g --username=uddezthursf9thpo --password=cApIZdrCriOROfE3LumI update
