name: Liquibase MySQL Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: bkxg4abnmdjq9yqqpy7g
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (needed for Liquibase)
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Liquibase CLI
        run: |
          curl -L "https://github.com/liquibase/liquibase/releases/download/v4.30.0/liquibase-4.30.0.tar.gz" -o liquibase.tar.gz
          tar -xzvf liquibase.tar.gz
          sudo mkdir -p /opt/liquibase
          sudo mv * /opt/liquibase/

      - name: Download MySQL JDBC Driver
        run: |
          # Clean up any existing file
          rm -f /opt/liquibase/lib/mysql-connector-java-8.0.32.jar
          # Download the MySQL JDBC Connector
          curl -L "https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.32/mysql-connector-java-8.0.32.jar" -o /opt/liquibase/lib/mysql-connector-java-8.0.32.jar
          # Verify download
          file /opt/liquibase/lib/mysql-connector-java-8.0.32.jar
          ls -l /opt/liquibase/lib

      - name: Set Environment Variables for Liquibase
        run: |
          echo "LIQUIBASE_HOME=/opt/liquibase" >> $GITHUB_ENV
          echo "CLASSPATH=/opt/liquibase/lib/mysql-connector-java-8.0.32.jar" >> $GITHUB_ENV

      - name: Run Liquibase update and check status
        run: |
          $LIQUIBASE_HOME/liquibase --url="jdbc:mysql://uddezthursf9thpo:cApIZdrCriOROfE3LumI@bkxg4abnmdjq9yqqpy7g-mysql.services.clever-cloud.com:3306/bkxg4abnmdjq9yqqpy7g" \
          --username=uddezthursf9thpo \
          --password=cApIZdrCriOROfE3LumI \
          --changelog-file=example-changelog.sql updatesql --logLevel=debug
